# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Wiki-Plugin-GeoCache
version:      0.2
version_from: lib/CGI/Wiki/Plugin/GeoCache.pm
installdirs:  site
requires:
    Carp:                          0
    CGI::Wiki:                     0.27
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
